### ISSUE TITLE
Weather temp is not showing 

### ISSUE THREAD

**Issue by xdgalaxy2** [ervans589/Meenimal-for-Rainmeter#2]
![Screenshot 2024-09-27 015351](https://github.com/user-attachments/assets/ccc133db-cb26-4f74-b7bd-ce794369e222)

**Comment by AKAgenius87** [comment]
same , restarting rainmeter as suggested does nothing
edit: and doesn't load spotify playing
![cc](https://github.com/user-attachments/assets/8d6fb319-3cb0-48a4-8fef-bff59cebbecc)

**Comment by stenakis** [comment]
In 24.11.23 version, the issue is fixed. Make sure to install the latest version from Gitub or DeviantArt.

**Comment by stenakis** [comment]
In 24.11.23 version, the issue is fixed. Make sure to install the latest version from Gitub or DeviantArt.
